version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: upirecon
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ingest-service:
    build: 
      context: ./ingest-service
#      dockerfile: ingest-service/Dockerfile
    container_name: ingest-service
    ports:
      - "8081:8081"
    volumes:
#      - ./ingest-service/src:/app/ingest-service/src
#      - ./:/app
      - ./ingest-service:/app           # mount source code
#      - ~/.m2:/root/.m2 
      - C:/Users/thega/.m2:/root/.m2
    depends_on:
      - kafka
      - postgres

  transaction-service:
    build: 
      context: ./transaction-service
#      dockerfile: transaction-service/Dockerfile
    container_name: transaction-service
    ports:
      - "8082:8082"
    volumes:
#      - ./transaction-service/src:/app/transaction-service/src
      - ./transaction-service:/app           # mount source code
      - C:/Users/thega/.m2:/root/.m2
#      - ./:/app
#      - ~/.m2:/root/.m2 
    depends_on:
      - kafka
      - postgres

  normalizer-service:
    build: 
      context: ./normalizer-service
#      dockerfile: normalizer-service/Dockerfile
    container_name: normalizer-service
    ports:
      - "8083:8083"
    volumes:
      - ./normalizer-service:/app           # mount source code
      - C:/Users/thega/.m2:/root/.m2
#      - ./:/app
#      - ~/.m2:/root/.m2 
    depends_on:
      - kafka
      - postgres

  recon-service:
    build: 
      context: ./recon-service
#      dockerfile: recon-service/Dockerfile
    container_name: recon-service
    ports:
      - "8084:8084"
    volumes:
      - ./recon-service:/app           # mount source code
#      - ./:/app
      - C:/Users/thega/.m2:/root/.m2
#      - ~/.m2:/root/.m2 
    depends_on:
      - kafka
      - postgres

  report-service:
    build: 
      context: ./report-service
#      dockerfile: report-service/Dockerfile
    container_name: report-service
    ports:
      - "8085:8085"
    volumes:
      - ./report-service:/app           # mount source code
#      - ./report-service/src:/app/src
#      - ~/.m2:/root/.m2 
#      - ./:/app
      - C:/Users/thega/.m2:/root/.m2
    depends_on:
      - kafka
      - postgres

volumes:
  pgdata:

