# src/main/resources/application.yml
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/upi_payment_recon
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent_output: true
    deserialization:
      fail-on-unknown-properties: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
     key-serializer: org.apache.kafka.common.serialization.StringSerializer
     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
     spring.json.add.type.headers: false  
