# src/main/resources/application.yml
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/upirecon
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent_output: true
    deserialization:
      fail-on-unknown-properties: true  
