# src/main/resources/application.yml
server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/upi_payment_recon
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent_output: true
    deserialization:
      fail-on-unknown-properties: true  

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: normalizer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
